### ISSUE TITLE
Events that go over several days are not displayed after start day

### ISSUE THREAD

**Issue by ifrik** [events-radar/drupal-make#117]
Events are displayed on the general list only if they started less than 6 hours ago. So events that continue over several days are missing, both in the individual group and on the general events list.

**Comment by ekes** [comment]
Well that was fun. Lots for something most people will (hopefully) not notice. Outline:
- Add OR filter to include events that continue or have finished in the last hour.
- Add custom theme output for 'radar_time' so that it shows increased granularity if the start and end times cross day, month or year boundaries.
- Rewrite the output of the day used to sort events into days in lists. Thus putting events that started before today into 'upcoming' lists (events search, and groups events).
- Reorder events within days so that long running events are at the bottom of the list (additionally added secondary sort on end date for all events).

**Comment by ekes** [comment]
Merged. Awaiting possible imported events cleanup before I deploy.
